LilycoveCity_DepartmentStore_3F_MapScripts::
	.byte 0

LilycoveCity_DepartmentStore_3F_EventScript_ClerkLeft::
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart LilycoveCity_DepartmentStore_3F_Pokemart_Vitamins
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
LilycoveCity_DepartmentStore_3F_Pokemart_Vitamins:
	.2byte ITEM_BIG_ROOT
	.2byte ITEM_BINDING_BAND
	.2byte ITEM_BLACK_BELT
	.2byte ITEM_BLACK_GLASSES
	.2byte ITEM_CHARCOAL
	.2byte ITEM_CHOICE_BAND
	.2byte ITEM_CHOICE_SCARF
	.2byte ITEM_CHOICE_SPECS
	.2byte ITEM_DRAGON_FANG
	.2byte ITEM_EXPERT_BELT
	.2byte ITEM_GRIP_CLAW
	.2byte ITEM_HARD_STONE
	.2byte ITEM_IRON_BALL
	.2byte ITEM_KINGS_ROCK
	.2byte ITEM_LIFE_ORB
	.2byte ITEM_LIGHT_BALL
	.2byte ITEM_LOADED_DICE
	.2byte ITEM_MAGNET
	.2byte ITEM_METAL_COAT
	.2byte ITEM_METRONOME
	.2byte ITEM_MIRACLE_SEED
	.2byte ITEM_MUSCLE_BAND
	.2byte ITEM_MYSTIC_WATER
	.2byte ITEM_NEVER_MELT_ICE
	.2byte ITEM_NORMAL_GEM
	.2byte ITEM_PIXIE_PLATE
	.2byte ITEM_POISON_BARB
	.2byte ITEM_POWER_HERB
	.2byte ITEM_PUNCHING_GLOVE
	.2byte ITEM_QUICK_CLAW
	.2byte ITEM_RAZOR_CLAW
	.2byte ITEM_RING_TARGET
	.2byte ITEM_SCOPE_LENS
	.2byte ITEM_SHARP_BEAK
	.2byte ITEM_SILK_SCARF
	.2byte ITEM_SILVER_POWDER
	.2byte ITEM_SOFT_SAND
	.2byte ITEM_SPELL_TAG
	.2byte ITEM_THROAT_SPRAY
	.2byte ITEM_TWISTED_SPOON
	.2byte ITEM_WEAKNESS_POLICY
	.2byte ITEM_WIDE_LENS
	.2byte ITEM_WISE_GLASSES
	.2byte ITEM_ZOOM_LENS
	.2byte ITEM_NONE
	release
	end

LilycoveCity_DepartmentStore_3F_EventScript_ClerkRight::
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart LilycoveCity_DepartmentStore_3F_Pokemart_StatBoosters
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
LilycoveCity_DepartmentStore_3F_Pokemart_StatBoosters:
	.2byte ITEM_ABILITY_SHIELD
	.2byte ITEM_ABSORB_BULB
	.2byte ITEM_ADRENALINE_ORB
	.2byte ITEM_AIR_BALLOON
	.2byte ITEM_ASSAULT_VEST
	.2byte ITEM_BLACK_SLUDGE
	.2byte ITEM_BLUNDER_POLICY
	.2byte ITEM_BRIGHT_POWDER
	.2byte ITEM_CELL_BATTERY
	.2byte ITEM_CLEAR_AMULET
	.2byte ITEM_COVERT_CLOAK
	.2byte ITEM_DAMP_ROCK
	.2byte ITEM_EJECT_BUTTON
	.2byte ITEM_EJECT_PACK
	.2byte ITEM_ELECTRIC_SEED
	.2byte ITEM_EVIOLITE
	.2byte ITEM_FLAME_ORB
	.2byte ITEM_FLOAT_STONE
	.2byte ITEM_FOCUS_SASH
	.2byte ITEM_GRASSY_SEED
	.2byte ITEM_HEAT_ROCK
	.2byte ITEM_HEAVY_DUTY_BOOTS
	.2byte ITEM_ICY_ROCK
	.2byte ITEM_LAGGING_TAIL
	.2byte ITEM_LEFTOVERS
	.2byte ITEM_LIGHT_CLAY
	.2byte ITEM_LUMINOUS_MOSS
	.2byte ITEM_MENTAL_HERB
	.2byte ITEM_METAL_POWDER
	.2byte ITEM_MIRROR_HERB
	.2byte ITEM_MISTY_SEED
	.2byte ITEM_PROTECTIVE_PADS
	.2byte ITEM_PSYCHIC_SEED
	.2byte ITEM_QUICK_POWDER
	.2byte ITEM_RED_CARD
	.2byte ITEM_ROCKY_HELMET
	.2byte ITEM_ROOM_SERVICE
	.2byte ITEM_SAFETY_GOGGLES
	.2byte ITEM_SHED_SHELL
	.2byte ITEM_SHELL_BELL
	.2byte ITEM_SMOOTH_ROCK
	.2byte ITEM_SNOWBALL
	.2byte ITEM_STICKY_BARB
	.2byte ITEM_TERRAIN_EXTENDER
	.2byte ITEM_TOXIC_ORB
	.2byte ITEM_UTILITY_UMBRELLA
	.2byte ITEM_WHITE_HERB
	.2byte ITEM_NONE
	release
	end

LilycoveCity_DepartmentStore_3F_EventScript_TriathleteM::
	msgbox LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_3F_EventScript_PokefanM::
	msgbox LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_3F_EventScript_Woman::
	msgbox LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon, MSGBOX_NPC
	end

LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon:
	.string "For quickly toughening up POKéMON,\n"
	.string "items are the best.\p"
	.string "PROTEIN boosts ATTACK,\n"
	.string "and CALCIUM raises SP. ATK.$"

LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance:
	.string "I want my POKéMON to have more\n"
	.string "endurance.\p"
	.string "I'm trying to decide whether to raise\n"
	.string "DEFENSE with IRON, or SP. DEF with ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon:
	.string "I gave a CARBOS to my POKéMON,\n"
	.string "and its SPEED went up.$"

